### ISSUE TITLE
Add Setup instructions

### ISSUE THREAD

**Issue by 0xT3chN0** [e-candeloro/SAURUSS-Autonomous-Drone-Surveillance#10]
Hi, Very cool project, but some basic setup inssstruction to get the Software + Hardware up and running would be nice.

Please keep up the great work!

**Comment by e-candeloro** [comment]
Hi, thanks for your feedback!
Unfortunately, this is only a project showcase page and I didn't (at the time) make all the instruction to replicate the setup, especially the hardware 😢, so sorry about that 😞
But I'm here if you need help for the code on the Arduino and the bridge finite state machine.
Regarding the android app and the drone, my colleagues coded those parts so I know only a little about them.

**Comment by 0xT3chN0** [comment]
Thanks. I think I'll order the parts on aliexpress and will try to set this up. 

There are some Sub-Folders in the Bridge_Raspberry folder, how would I setup the Raspberry to get the Bridge up and running?

**Comment by e-candeloro** [comment]
No problem!
We actually didn't use raspberry at the end but is is completely possible. We had issue installing opencv on it for the tello drone autopilot. But now there are other methods to install opencv to raspberry. 
If you only want to operate the bridge fsm you don't need opencv tough.

For the setup I can only tell you the things I did for the module Bridge Comm that I coded. For the other parts unfortunately I can't help much.

There is a requirements.txt file that you can use to install all the libraries and should work.
Here's a link that could be useful: [https://note.nkmk.me/en/python-pip-install-requirements/](https://note.nkmk.me/en/python-pip-install-requirements/)

**Comment by 0xT3chN0** [comment]
Ah, that's cool, because I don't want to use a Raspberry either unless it's absolutely necessary.

Is there something like a main program that can start everything at once?

**Comment by e-candeloro** [comment]
Yes, it's the bridge comm script inside the bridge comm folder
